name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    strategy:
      matrix:
        include:
          - os: windows-latest
            make-targets: --targets @electron-forge/maker-msix --platform win32
          - os: macos-latest
            make-targets: --targets @electron-forge/maker-zip --platform darwin
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Publish
        run: yarn publish ${{ matrix.make-targets }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
